---
Linux:
  MalPaths:
    - /.Library/
    - /.Library/SystemServices/updateSystem
    - /.Library/SystemNetwork
    - /.Library/log.txt

Windows:
  MalPaths:
    - C:\\ProgramData\\SystemData
    - C:\\ProgramData\\RecoverySystem
  MalFiles:
    - C:\\ProgramData\\RecoverySystem\\msg.exe
    - C:\\ProgramData\\RecoverySystem\\recoveryWindows.zip 
    - C:\\ProgramData\\SystemData\\igfxCUIService.exe
    - C:\\ProgramData\\SystemData\\microsoft_Windows.dll
    - C:\\ProgramData\\RecoverySystem\\recoveryWindows.zip
    - C:\\ProgramData\\SystemData\\tempo1.txt
    - C:\\ProgramData\\SystemData\\tempo2.txt
    - C:\\ProgramData\\SystemData\\tempi1.txt
    - C:\\ProgramData\\SystemData\\tempi2.txt
    - C:\\ProgramData\\SystemData\\temps1.txt
    - C:\\ProgramData\\SystemData\\temps2.txt
    - C:\\ProgramData\\SystemData\\tempu.txt
    - C:\\ProgramData\\SystemData\\microsoft_windows.dll
    - C:\\ProgramData\\xAE Operating System\\ServiceHub.exe
  MalCommands:
    - "\"C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe\" getmac | Out-File -Encoding 'Default' 'C:\\ProgramData\\SystemData\\temps1.txt' ; wmic path win32_physicalmedia get SerialNumber | Out-File -Encoding 'Default' 'C:\\ProgramData\\SystemData\\temps2.txt'"
    - "\"C:\\Windows\\System32\\Wbem\\WMIC.exe\"  path win32_physicalmedia get SerialNumber"
    - "\"C:\\Windows\\system32\\getmac.exe\""
    - "\"C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe\" $env:username | Out-File -Encoding 'Default' 'C:\\ProgramData\\SystemData\\tempu.txt'"
    - "\"C:\\Windows\\System32\\cmd.exe\" /c wmic OS get Caption, CSDVersion, OSArchitecture, Version / value > \"C:\\ProgramData\\SystemData\\tempo1.txt\" && type \"C:\\ProgramData\\SystemData\\tempo1.txt\" > \"C:\\ProgramData\\SystemData\\tempo2.txt\""
    - "wmic  OS get Caption, CSDVersion, OSArchitecture, Version / value  "
    - "\"C:\\Windows\\System32\\cmd.exe\" /c wmic nicconfig where 'IPEnabled = True' get ipaddress > \"C:\\ProgramData\\SystemData\\tempi1.txt\" && type \"C:\\ProgramData\\SystemData\\tempi1.txt\" > \"C:\\ProgramData\\SystemData\\tempi2.txt\""
    - "wmic  nicconfig where 'IPEnabled = True' get ipaddress  "
    - "\"C:\\Windows\\System32\\cmd.exe\" /c REG ADD HKCU\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run /V igfxCUIService /t REG_SZ /D \"C:\\ProgramData\\SystemData\\igfxCUIService.exe\" /F"
    - "REG  ADD HKCU\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run /V igfxCUIService /t REG_SZ /D \"C:\\ProgramData\\SystemData\\igfxCUIService.exe\" /F"

Darwin:
  MalPaths:
    - /Library/MacOsServices
    - /Library/SystemNetwork
  MalFiles:
    - /Library/MacOsServices/updateMacOs
    - /Library/LaunchAgents/com.apple.update.plist
  MalStrings:
    - 1W64PQQxrwY3XjBnv_QAeBQu-ePr537eu
    - welcome to extenal app
    - updateMacOs
    - /Users/mac/Desktop/test/test/json.hpp
  MalCommands:
    - ">/dev/null 2>&1 &"
    - "chmod 0777"
    - "unzip -o"
    - "whoami"