---
Linux:
  - /.Library/
  - /.Library/SystemServices/updateSystem
  - /.Library/SystemNetwork
  - /.Library/log.txt

Windows:
  - C:\ProgramData\SystemData 
  - C:\ProgramData\SystemData\igfxCUIService.exe
  - C:\ProgramData\SystemData\microsoft_Windows.dll

macOS:
  - /Library/MacOsServices
  - /Library/MacOsServices/updateMacOs
  - /Library/SystemNetwork
  - /Library/LaunchAgents/com.apple.update.plist